version: '3.8'

services:
  db:
    image: postgres:16.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: store
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "wal_level=logical"]

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command: start-dev --import-realm
    container_name: keycloak-local
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8082
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - keycloak-db
    ports:
      - "8082:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import

  keycloak-db:
    image: postgres:16.2
    container_name: keycloak-db
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    ports:
      - "5656:5432"
    volumes:
      - postgres-data-keycloak:/var/lib/postgresql/keycloak/data/

volumes:
  postgres_data:
  postgres-data-keycloak:
  redis_data:
    driver: local


