INSERT INTO product (id, description) VALUES
                                   (1, 'Wireless Mouse'),
                                   (2, 'Gaming Headset'),
                                   (3, 'Bluetooth Speaker'),
                                   (4, 'Laptop Stand'),
                                   (5, 'Smartphone Case'),
                                   (6, 'Portable Charger'),
                                   (7, 'LED Desk Lamp'),
                                   (8, 'Mechanical Keyboard'),
                                   (9, '4K Monitor'),
                                   (10, 'USB-C Hub'),
                                   (11, 'Smartwatch'),
                                   (12, 'Noise Cancelling Headphones'),
                                   (13, 'Gaming Mouse Pad'),
                                   (14, 'Smart Thermostat'),
                                   (15, 'Action Camera'),
                                   (16, 'Fitness Tracker'),
                                   (17, 'Laptop Bag'),
                                   (18, 'Wireless Charger'),
                                   (19, 'Phone Stand'),
                                   (20, 'Bluetooth Earbuds'),
                                   (21, 'Power Bank'),
                                   (22, 'Car Phone Mount'),
                                   (23, 'Digital Camera'),
                                   (24, 'Smart TV'),
                                   (25, 'Robot Vacuum Cleaner'),
                                   (26, 'Tablet Sleeve'),
                                   (27, 'Fitness Resistance Bands'),
                                   (28, 'Mini Projector'),
                                   (29, 'Electric Toothbrush'),
                                   (30, 'Portable Fan'),
                                   (31, 'Smart Home Security Camera'),
                                   (32, 'Wi-Fi Extender'),
                                   (33, 'Solar Power Bank'),
                                   (34, 'VR Headset'),
                                   (35, 'Laptop Cooling Pad'),
                                   (36, 'Smart Light Bulbs'),
                                   (37, 'Cordless Drill'),
                                   (38, 'Bluetooth Tracking Tags'),
                                   (39, 'Smart Plugs'),
                                   (40, 'Air Purifier'),
                                   (41, 'Mini Fridge'),
                                   (42, 'Electric Kettle'),
                                   (43, 'Cordless Vacuum Cleaner'),
                                   (44, 'Digital Thermometer'),
                                   (45, 'Under Desk Drawer'),
                                   (46, 'Smart Lock'),
                                   (47, 'Portable Bluetooth Speaker'),
                                   (48, 'Multi-tool Kit'),
                                   (49, 'Noise Machine'),
                                   (50, 'Smart Coffee Mug'),
                                   (51, 'PopSocket'),
                                   (52, 'Portable Projector Screen'),
                                   (53, 'Electric Griddle'),
                                   (54, 'Smart Mirror'),
                                   (55, 'Surge Protector'),
                                   (56, 'Electric Pressure Cooker'),
                                   (57, 'Steam Iron'),
                                   (58, 'Mini Blender'),
                                   (59, 'Electric Wine Opener'),
                                   (60, 'Electric Can Opener'),
                                   (61, 'Cookbook Stand'),
                                   (62, 'Tactical Flashlight'),
                                   (63, 'Smart Scale'),
                                   (64, 'Motion Sensor Light'),
                                   (65, 'Mini Fan'),
                                   (66, 'Instant Pot'),
                                   (67, 'Noise Cancelling Earphones'),
                                   (68, 'Waterproof Speaker'),
                                   (69, 'Treadmill Desk'),
                                   (70, 'Smart Plugs'),
                                   (71, 'Smart Doorbell'),
                                   (72, 'Electric Grill'),
                                   (73, 'Smart Refrigerator'),
                                   (74, 'Wine Cooler'),
                                   (75, 'Electric Skillet'),
                                   (76, 'Car Vacuum Cleaner'),
                                   (77, 'Smart Thermometer'),
                                   (78, 'Egg Cooker'),
                                   (79, 'Touchscreen Thermostat'),
                                   (80, 'Smart Air Conditioner'),
                                   (81, 'Power Strip'),
                                   (82, 'Cordless Electric Screwdriver'),
                                   (83, 'Smart Lock Box'),
                                   (84, 'Voice Assistant Device'),
                                   (85, 'Electric Broom'),
                                   (86, 'Kitchen Timer'),
                                   (87, 'Water Bottle with UV Sterilizer'),
                                   (88, 'Electric Pepper Grinder'),
                                   (89, 'Car Jump Starter'),
                                   (90, 'Portable Air Conditioner'),
                                   (91, 'Electronic Luggage Scale'),
                                   (92, 'Electronic Puzzle Game'),
                                   (93, 'Heat Resistance Gloves'),
                                   (94, 'Smart Oven'),
                                   (95, 'Solar Charger'),
                                   (96, 'Portable Grill'),
                                   (97, 'Electric Nail File'),
                                   (98, 'Hair Straightener'),
                                   (99, 'Smart Door Lock'),
                                   (100, 'Ultrasonic Jewelry Cleaner'),
                                   (101, 'Ice Cream Maker'),
                                   (102, 'Cordless Hair Curler'),
                                   (103, 'Smartphone Stabilizer'),
                                   (104, 'Smart Bike Lock'),
                                   (105, 'Self-Cleaning Water Bottle'),
                                   (106, 'Electric Razor'),
                                   (107, 'Digital Art Frame'),
                                   (108, 'Bluetooth Beanie Hat'),
                                   (109, 'Sleep Mask with Bluetooth'),
                                   (110, 'Wireless Security Camera'),
                                   (111, 'Laser Measure Tool'),
                                   (112, 'Handheld Steamer'),
                                   (113, 'Voice-Activated Smart Light'),
                                   (114, 'Smart Home Hub'),
                                   (115, 'Digital Piano'),
                                   (116, 'Wireless Power Bank'),
                                   (117, 'Smart Wall Clock'),
                                   (118, 'Fitness Smart Watch'),
                                   (119, 'Handheld Vacuum Cleaner'),
                                   (120, 'Smart Air Purifier'),
                                   (121, 'Rotating Desk Fan'),
                                   (122, 'Ice Maker'),
                                   (123, 'Wine Glass Holder'),
                                   (124, 'Multi-Function Air Fryer'),
                                   (125, 'Personal Blender'),
                                   (126, 'Smart Socket'),
                                   (127, 'Bluetooth Sleep Mask'),
                                   (128, 'Pet Feeder'),
                                   (129, 'Electric Fish Tank Cleaner'),
                                   (130, 'Electric Slicer'),
                                   (131, 'Mini Ice Cream Maker'),
                                   (132, 'Wi-Fi Coffee Maker'),
                                   (133, 'Cordless Drill Set'),
                                   (134, 'Electric Pedicure Kit'),
                                   (135, 'Bluetooth Meat Thermometer'),
                                   (136, 'Fitness Jump Rope'),
                                   (137, 'Electric Pressure Washer'),
                                   (138, 'Personal Fan'),
                                   (139, 'Fitness Mat'),
                                   (140, 'Smart Ceiling Fan'),
                                   (141, 'Portable Espresso Maker'),
                                   (142, 'Portable Phone Charger'),
                                   (143, 'Bluetooth Shower Speaker'),
                                   (144, 'Rechargeable Battery Pack'),
                                   (145, 'Electric Foot Massager'),
                                   (146, 'Air Freshener'),
                                   (147, 'Smart Mirror with Touchscreen'),
                                   (148, 'Automatic Plant Watering System'),
                                   (149, 'Smart Wearable Camera'),
                                   (150, 'Electric Bottle Opener'),
                                   (151, 'Blender with Touchscreen'),
                                   (152, 'Self-Watering Planter'),
                                   (153, 'Portable Humidifier'),
                                   (154, 'Smart Home Smoke Detector'),
                                   (155, 'Smart Garden Planter'),
                                   (156, 'Smart Key Finder'),
                                   (157, 'Voice Assistant Light Bulb'),
                                   (158, 'Electric Hand Warmer'),
                                   (159, 'Portable Heater'),
                                   (160, 'Personal Water Filter'),
                                   (161, 'Smart Motion Detector'),
                                   (162, 'Electric Mop'),
                                   (163, 'Smart Shower Head'),
                                   (164, 'Portable Wine Chiller'),
                                   (165, 'Bluetooth Keychain'),
                                   (166, 'Electric Toothbrush Sanitizer'),
                                   (167, 'Smart Bathroom Scale'),
                                   (168, 'Car Phone Charger'),
                                   (169, 'Mini Projector Stand'),
                                   (170, 'Smart Curtain Controller'),
                                   (171, 'Pet Camera'),
                                   (172, 'Battery-Powered Lantern'),
                                   (173, 'Smart Thermostat with Voice Control'),
                                   (174, 'Phone Holder for Car'),
                                   (175, 'Smart Electric Grill'),
                                   (176, 'Smart Handheld Vacuum'),
                                   (177, 'Solar Garden Lights'),
                                   (178, 'Smart Light Bulb with RGB'),
                                   (179, 'Smart Watering System'),
                                   (180, 'Smart Faucet'),
                                   (181, 'Electric Drain Cleaner'),
                                   (182, 'Wi-Fi Electric Kettle'),
                                   (183, 'Electric Juice Extractor'),
                                   (184, 'Smart Wireless Router'),
                                   (185, 'Cordless Weed Eater'),
                                   (186, 'Smart Water Filter'),
                                   (187, 'Wireless Charging Dock'),
                                   (188, 'Voice-Controlled Fan'),
                                   (189, 'Electric Blade Sharpening Tool'),
                                   (190, 'Cordless Outdoor Light'),
                                   (191, 'Digital Speedometer'),
                                   (192, 'Mini Hand Warmer'),
                                   (193, 'Smart Refrigerator with Wi-Fi'),
                                   (194, 'Remote-Controlled Ceiling Fan'),
                                   (195, 'Rechargeable Electric Screwdriver'),
                                   (196, 'Portable Karaoke Machine'),
                                   (197, 'Electric Kettle with Temperature Control'),
                                   (198, 'Electric Ice Cream Freezer'),
                                   (199, 'Smart Iron'),
                                   (200, 'Self-Heating Blanket'),
                                   (201, 'Digital Radio'),
                                   (202, 'Smart Home Fridge'),
                                   (203, 'Electric Aromatherapy Diffuser'),
                                   (204, 'Smart Juicer'),
                                   (205, 'Cordless Chainsaw'),
                                   (206, 'Electric Pasta Maker'),
                                   (207, 'Bluetooth Shower Head'),
                                   (208, 'Smart Solar Panel Charger'),
                                   (209, 'Mini Herb Garden'),
                                   (210, 'Smart Scent Diffuser'),
                                   (211, 'Electric Slush Machine'),
                                   (212, 'Smart Toilet Paper Dispenser'),
                                   (213, 'Voice-Controlled Air Conditioner'),
                                   (214, 'Electric Grill with Thermostat'),
                                   (215, 'Smart Vacuum Sealer'),
                                   (216, 'Solar-powered Phone Charger'),
                                   (217, 'Rechargeable Smart Toothbrush'),
                                   (218, 'Smart Cooktop'),
                                   (219, 'Electric Pizza Oven'),
                                   (220, 'Electric Heating Pad'),
                                   (221, 'Smart Solar Water Heater'),
                                   (222, 'Smart Digital Lock'),
                                   (223, 'Wi-Fi Home Security System'),
                                   (224, 'Wireless Charging Stand'),
                                   (225, 'Portable Battery Pack'),
                                   (226, 'Electric Mosquito Trap'),
                                   (227, 'Electric Pressure Cooker with Wifi'),
                                   (228, 'Smart Phone Holder'),
                                   (229, 'Bluetooth Tracker'),
                                   (230, 'Car Battery Charger'),
                                   (231, 'Electric Cooker'),
                                   (232, 'Smart Under Cabinet Light'),
                                   (233, 'Electric Grater'),
                                   (234, 'Smart Plug with Energy Monitor'),
                                   (235, 'Smart Bathroom Mirror'),
                                   (236, 'Mini Food Processor'),
                                   (237, 'Electric Panini Press'),
                                   (238, 'Car LED Headlights'),
                                   (239, 'Bluetooth Soundbar'),
                                   (240, 'Mini Air Purifier'),
                                   (241, 'Smart Air Conditioner'),
                                   (242, 'Bluetooth Smart Scale'),
                                   (243, 'Pet Door Sensor'),
                                   (244, 'Smart Fan with Humidity Control'),
                                   (245, 'Electric Smart Lock'),
                                   (246, 'Smart Humidifier'),
                                   (247, 'Smart Glasses'),
                                   (248, 'Smart Toothbrush Holder'),
                                   (249, 'Bluetooth Smart Lock'),
                                   (250, 'Smart Electric Kettle'),
                                   (251, 'Wireless Pet Collar'),
                                   (252, 'Electric Bacon Cooker'),
                                   (253, 'Smart Garden Light'),
                                   (254, 'Bluetooth Wireless Keypad'),
                                   (255, 'Smart Window Blinds'),
                                   (256, 'Cordless Window Cleaner'),
                                   (257, 'Smart Water Sprinkler'),
                                   (258, 'Voice-Controlled Wall Light'),
                                   (259, 'Rechargeable Car Jump Starter'),
                                   (260, 'Electric Steak Thermometer'),
                                   (261, 'Smart Fridge Organizer'),
                                   (262, 'Car Rearview Camera'),
                                   (263, 'Smart Indoor Garden'),
                                   (264, 'Electric Facial Steamer'),
                                   (265, 'Cordless Lawn Mower'),
                                   (266, 'Smart Mirror with Bluetooth'),
                                   (267, 'Pet Tracking Collar'),
                                   (268, 'Smart Traffic Light'),
                                   (269, 'Smart Socket with Timer'),
                                   (270, 'Electric Soldering Iron'),
                                   (271, 'Smart Home Assistant'),
                                   (272, 'Solar Battery Pack'),
                                   (273, 'Digital Projector'),
                                   (274, 'Electric Citrus Juicer'),
                                   (275, 'Smart Home Audio System'),
                                   (276, 'Smart Trash Can'),
                                   (277, 'Smart Led Bulb with App'),
                                   (278, 'Rechargeable Fan'),
                                   (279, 'Smart Thermostat with Voice'),
                                   (280, 'Electric Egg Boiler'),
                                   (281, 'Wireless Bluetooth Camera'),
                                   (282, 'Cordless Power Washer'),
                                   (283, 'Smart Baby Monitor'),
                                   (284, 'Smart Speaker with Alexa'),
                                   (285, 'Portable Air Cooler'),
                                   (286, 'Smart Digital Door Lock'),
                                   (287, 'Electric Dustbin'),
                                   (288, 'Voice-Activated Smart Speaker'),
                                   (289, 'Smart Security Camera System'),
                                   (290, 'Electric Hair Curler'),
                                   (291, 'Smart Electric Heater'),
                                   (292, 'Smart Plant Monitor'),
                                   (293, 'Electric Meat Grinder'),
                                   (294, 'Smart Coffee Machine'),
                                   (295, 'Cordless Saw'),
                                   (296, 'Portable Water Pump'),
                                   (297, 'Smart Outdoor Light'),
                                   (298, 'Electric Pizza Stone'),
                                   (299, 'Cordless Power Tool'),
                                   (300, 'Smart Timer'),
                                   (301, 'Wireless Speaker with Lights'),
                                   (302, 'Electric Shaver'),
                                   (303, 'Smart Remote Control'),
                                   (304, 'Cordless Carpet Cleaner'),
                                   (305, 'Electric LED Strip Lights'),
                                   (306, 'Smart Curtain Motor'),
                                   (307, 'Smart Indoor Thermometer'),
                                   (308, 'Wireless Home Speaker'),
                                   (309, 'Smart Sound System'),
                                   (310, 'Smart Air Heater'),
                                   (311, 'Electric Oven Thermometer'),
                                   (312, 'Smart Vacuum Cleaner'),
                                   (313, 'Bluetooth Wall Clock'),
                                   (314, 'Smart Projector'),
                                   (315, 'Solar Water Pump'),
                                   (316, 'Electric Sauté Pan'),
                                   (317, 'Smart Speaker System'),
                                   (318, 'Smart Smartwatch Charger'),
                                   (319, 'Wireless Bluetooth Headphones'),
                                   (320, 'Smart Lightstrip'),
                                   (321, 'Electric Waffle Maker'),
                                   (322, 'Cordless Snow Blower'),
                                   (323, 'Smart Wireless Charger'),
                                   (324, 'Smart Sink Faucet'),
                                   (325, 'Electric Fruit Peeler'),
                                   (326, 'Smart Washing Machine'),
                                   (327, 'Electric Grill Pan'),
                                   (328, 'Smart Heating Blanket'),
                                   (329, 'Smart Car Charger'),
                                   (330, 'Electric Hand Mixer'),
                                   (331, 'Smart Umbrella'),
                                   (332, 'Smart Home Automation Kit'),
                                   (333, 'Smart Digital Thermometer'),
                                   (334, 'Portable Wireless Charger'),
                                   (335, 'Bluetooth Fitness Tracker'),
                                   (336, 'Smart Foldable Desk'),
                                   (337, 'Cordless Air Compressor'),
                                   (338, 'Smart LED Lightbulbs'),
                                   (339, 'Smart Electric Blanket'),
                                   (340, 'Electric Ice Cream Maker'),
                                   (341, 'Smart Coffee Pod Machine'),
                                   (342, 'Smart Bluetooth Device'),
                                   (343, 'Bluetooth Bike Tracker'),
                                   (344, 'Smart Contact Lenses'),
                                   (345, 'Electric Ice Maker'),
                                   (346, 'Smart Phone Charger Stand'),
                                   (347, 'Bluetooth Electric Skateboard'),
                                   (348, 'Smart Exercise Bike'),
                                   (349, 'Wireless Home Security System'),
                                   (350, 'Electric Flashlight'),
                                   (351, 'Smart Water Bottle'),
                                   (352, 'Wireless Bluetooth Speaker'),
                                   (353, 'Smart Home System'),
                                   (354, 'Electric Charcoal Grill'),
                                   (355, 'Smart Fridge'),
                                   (356, 'Cordless Power Brush'),
                                   (357, 'Smart Power Strip'),
                                   (358, 'Portable Air Heater'),
                                   (359, 'Electric Pillow'),
                                   (360, 'Smart Bed Heater'),
                                   (361, 'Smart Refrigerator with Camera'),
                                   (362, 'Electric Meat Slicer'),
                                   (363, 'Smart Assistant Device'),
                                   (364, 'Portable Solar Charger'),
                                   (365, 'Smart Home Theater System'),
                                   (366, 'Smart Light Bulb with App Control'),
                                   (367, 'Smart TV Box'),
                                   (368, 'Bluetooth Key Finder'),
                                   (369, 'Cordless Window Vacuum'),
                                   (370, 'Smart Speaker with Touchscreen'),
                                   (371, 'Smart Fingerprint Door Lock'),
                                   (372, 'Smart Solar Charger'),
                                   (373, 'Smart Wireless Air Purifier'),
                                   (374, 'Smart LED Night Light'),
                                   (375, 'Portable Smart Projector'),
                                   (376, 'Electric Pizza Oven'),
                                   (377, 'Smart Air Freshener'),
                                   (378, 'Electric Hand Blender'),
                                   (379, 'Smart Water Dispenser'),
                                   (380, 'Portable Laptop Charger'),
                                   (381, 'Smart Fitness Band'),
                                   (382, 'Electric Tea Kettle'),
                                   (383, 'Smart Baby Camera'),
                                   (384, 'Electric Knife'),
                                   (385, 'Smart Blinds'),
                                   (386, 'Smart Home Automation'),
                                   (387, 'Electric Thermos Flask'),
                                   (388, 'Smart Security Doorbell'),
                                   (389, 'Smart Digital Scale'),
                                   (390, 'Electric Pressure Cooker'),
                                   (391, 'Smart Phone Holder for Car'),
                                   (392, 'Bluetooth Voice Recorder'),
                                   (393, 'Smart Clock with Wi-Fi'),
                                   (394, 'Electric Stir Fryer'),
                                   (395, 'Smart Gaming Chair'),
                                   (396, 'Smart Window Shade'),
                                   (397, 'Smart Water Cooler'),
                                   (398, 'Portable Fan with Lights'),
                                   (399, 'Smart Air Purifier with App'),
                                   (400, 'Smart Phone Grip'),
                                   (401, 'Smart Fitness Equipment'),
                                   (402, 'Electric Electric Grater'),
                                   (403, 'Smart Home Controller'),
                                   (404, 'Smart Home Security System'),
                                   (405, 'Electric Hand Warmer'),
                                   (406, 'Smart Light Strip'),
                                   (407, 'Bluetooth Electric Heater'),
                                   (408, 'Smart Solar Light'),
                                   (409, 'Portable Bluetooth Speaker'),
                                   (410, 'Smart Home Smoke Detector'),
                                   (411, 'Electric Rice Cooker'),
                                   (412, 'Smart Phone Charger'),
                                   (413, 'Smart Microwave'),
                                   (414, 'Electric Boiling Pot'),
                                   (415, 'Smart Smartwatch'),
                                   (416, 'Smart Electric Hair Brush'),
                                   (417, 'Smart Pizza Oven'),
                                   (418, 'Electric Food Dehydrator'),
                                   (419, 'Smart Desk Lamp'),
                                   (420, 'Smart Cleaning Robot'),
                                   (421, 'Smart LED Lights'),
                                   (422, 'Smart Ironing Board'),
                                   (423, 'Smart Digital Projector'),
                                   (424, 'Smart Home Control Hub'),
                                   (425, 'Smart USB Hub'),
                                   (426, 'Smart Battery Charger'),
                                   (427, 'Smart Smartwatch Stand'),
                                   (428, 'Electric Oven'),
                                   (429, 'Smart Desk Fan'),
                                   (430, 'Electric Milk Frother'),
                                   (431, 'Smart Home Assistant'),
                                   (432, 'Electric Deep Fryer'),
                                   (433, 'Smart Cooking Pot'),
                                   (434, 'Smart Mirror for Fitness'),
                                   (435, 'Electric Instant Water Heater'),
                                   (436, 'Smart Plumber'),
                                   (437, 'Smart Robot Vacuum'),
                                   (438, 'Smart Dishwasher'),
                                   (439, 'Electric Stainless Steel Grill'),
                                   (440, 'Smart Alarm Clock'),
                                   (441, 'Smart Garden Tool'),
                                   (442, 'Smart Pet Tracker'),
                                   (443, 'Smart Home Security Camera'),
                                   (444, 'Smart Wi-Fi Light Bulb'),
                                   (445, 'Smart Humidifier with Wifi'),
                                   (446, 'Smart Pet Feeder'),
                                   (447, 'Smart Phone Screen Protector'),
                                   (448, 'Smart Home Automation Kit'),
                                   (449, 'Smart Speaker System'),
                                   (450, 'Smart Fingerprint Scanner'),
                                   (451, 'Smart Thermostat for Home'),
                                   (452, 'Smart Coffee Brewer'),
                                   (453, 'Smart Desk Organizer'),
                                   (454, 'Smart Electrical Outlet'),
                                   (455, 'Smart Lock System'),
                                   (456, 'Smart Fridge Organizer'),
                                   (457, 'Smart Light Bulb for Bedroom'),
                                   (458, 'Smart Washer Dryer Combo'),
                                   (459, 'Smart Oven with Camera'),
                                   (460, 'Smart Home Automation Hub'),
                                   (461, 'Smart Solar Charger System'),
                                   (462, 'Smart Smart Plug'),
                                   (463, 'Smart Electric Water Kettle'),
                                   (464, 'Smart Projector System'),
                                   (465, 'Smart Doorbell with Camera'),
                                   (466, 'Smart Pressure Cooker'),
                                   (467, 'Smart Blender with Wi-Fi'),
                                   (468, 'Smart Egg Cooker'),
                                   (469, 'Smart Speaker for Home'),
                                   (470, 'Smart Gaming Console'),
                                   (471, 'Smart Home Wi-Fi Router'),
                                   (472, 'Smart Foot Massager'),
                                   (473, 'Smart Thermostat with Wifi Control'),
                                   (474, 'Smart Rechargeable Fan'),
                                   (475, 'Smart Handheld Vacuum Cleaner'),
                                   (476, 'Smart Fan with Smart Control'),
                                   (477, 'Smart Home Water Filter'),
                                   (478, 'Smart Bluetooth Speaker'),
                                   (479, 'Smart Wireless Vacuum Cleaner'),
                                   (480, 'Smart Phone Camera Lens'),
                                   (481, 'Smart Car Parking System'),
                                   (482, 'Smart LED Panel'),
                                   (483, 'Smart Wireless Air Purifier'),
                                   (484, 'Smart Window Fan'),
                                   (485, 'Smart Cooktop with Wi-Fi'),
                                   (486, 'Smart Vacuum Sealer'),
                                   (487, 'Smart Air Conditioner with Wi-Fi'),
                                   (488, 'Smart Electric Toothbrush'),
                                   (489, 'Smart Electric Grill'),
                                   (490, 'Smart Electric Water Heater'),
                                   (491, 'Smart Coffee Mug with Temperature Control'),
                                   (492, 'Smart Solar Panel System'),
                                   (493, 'Smart Wine Refrigerator'),
                                   (494, 'Smart Air Compressor'),
                                   (495, 'Smart Pet Feeder with Camera'),
                                   (496, 'Smart Electric Toothbrush with UV Sterilizer'),
                                   (497, 'Smart Fridge with Smart Lock'),
                                   (498, 'Smart Home Light System'),
                                   (499, 'Smart Bathroom Mirror'),
                                   (500, 'Smart Home Air Purifier');
