name: Build and Run Docker Container

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build project
        run: ./gradlew clean build

      - name: Run tests
        run: ./gradlew test

      - name: Build Docker image
        run: docker build -t store-service:latest .

      - name: Stop and remove existing Docker container
        run: |
          if [ "$(docker ps -q -f name=store-service)" ]; then
            docker stop store-service
            docker rm store-service
          fi

      - name: Run Docker container
        run: |
          docker run -d --name store-service -p 9090:8080 -e 'SPRING_PROFILES_ACTIVE=local' store-service:latest

      - name: Clean up Docker image
        if: always()  # This ensures cleanup runs even if there are errors in previous steps
        run: docker rmi store-service:latest
