name: Build and Run Docker Container

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build project with debug logs
        run: ./gradlew clean build --info

      - name: Run tests with detailed reports
        run: ./gradlew test --stacktrace --info

      - name: Upload test reports if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/store-service:latest .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/store-service:latest

      - name: Capture Docker logs if build fails
        if: failure()
        run: docker logs store-service > container-logs.txt || true

      - name: Upload Docker logs for debugging
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-container-logs
          path: container-logs.txt

      - name: Clean up Docker container and image
        if: always()
        run: |
          if [ "$(docker ps -q -f name=store-service)" ]; then
            docker stop store-service
            docker rm store-service
          fi
          docker rmi store-service:latest || true
